[package]
name = "anerror"
version = "1.0.0"
edition = "2021"

authors = ["Kyllingene"]
license = "MIT"

[dependencies]
anerror-macros = { path = "anerror-macros" }
anerror-error = { path = "anerror-error" }

