[package]
name = "errata"
version = "1.1.1"
edition = "2021"

authors = ["Kyllingene"]
license = "MIT"
description = "Ergonomic pretty error handling for binaries."
repository = "https://github.com/Kyllingene/errata"

[dependencies]
errata-macros = "0.1.0"

[workspace]
members = ["errata-macros"]

