[package]
name = "anerror"
version = "1.1.0"
edition = "2021"

authors = ["Kyllingene"]
license = "MIT"

[dependencies]
anerror-macros = { path = "anerror-macros" }

[workspace]
members = ["anerror-macros"]

